### PR TITLE
Voting with keys

### PR DESCRIPTION
**Pull request by hider**
Support voting by keyboard keys. Added page title.

### CODE REVIEW

**Review by garricasaurus — CHANGES_REQUESTED** [review]
My personal preference would be to assign the "shortcut" concept to the `VoteOption` model, and generate the shortcut keys to votes map statically using the HTML template. For example:

In `option.go`:

```
var VoteOptions = []*VoteOption{
	{Text: "½", Value: 0.5, Shortcut: "`"},
	{Text: "1", Value: 1, Shortcut: "1"},
        {Text: "2", Value: 2, Shortcut: "2"},
        [...]
}
type VoteOption struct {
   [...]
   Shortcut string
}
func (v *VoteOption) HasShortcut() bool {
	return v.Shortcut != ""
}
```
And then in `scripts.html`:

```
const shortcuts = new Map();
{{ range .options }}
{{ if .HasShortcut }}
shortcuts.set("{{ .Shortcut }}", "{{ .Value }}");
{{ end }}
{{ end }}
```
Put an `accesskey` attribute on the `input` element into `voting-form.html`:
```
<input
    name="votes"
    type="radio" 
    {{ if .HasShortcut }}
    accesskey="{{ .Shortcut }}"
    {{ end }}
[...]
```
And then the custom keyboard event listener, to avoid pressing the ALT, SHIFT etc to activate the `accesskey`:
```
function onKeyUp(e) {
    const key = e.key
    const vote = shortcuts.get(key)
    if (vote) {
        const input = document.querySelector(`input[accesskey="${key}"]`);
        if (input) {
            input.click();
        }
    }
}
```

**Comment by hider** [comment]
Added the _shortcut_ to the model and _accesskey_ to the input. However querying the inputs at page load is still better than separating the logic into two files.

**Comment by garricasaurus** [comment]
I'm not convinced it's better to query them on page load. Maybe it is, but the separation is already there anyways, and serves a different purpose:
   - the `scripts.js` file in `assets` contains "static" scripts, and can be cached by the browser
   - the `scripts.html` template in `templates` includes the above file, and contains additional generated pieces from the server state

**Comment by garricasaurus** [comment]
added an alternative PR for the same (for reference)
https://github.com/garricasaurus/pp-next/pull/14

**Comment by hider** [comment]
ok, merge #14 then

**Pull request closed without merging**
